#!/usr/bin/env python3
"""Generate the FL4.4 human-readable starting naval content report.

Reads assets/<scenario>_naval_forces.json (the same file
scripts/simulation/starting_naval_forces.gd validates and loads at runtime)
and writes a markdown table of every starting fleet's provenance and review
state to docs/roadmap/naval/g1_finish_line/evidence/FL4_2_STARTING_CONTENT_REPORT.md,
per 04_FL4_STARTING_CONTENT_AND_LEADERS.md's "Generate a human-readable
content report with unresolved review states" exit-evidence bullet.

This is a read-only report generator, not a second validator: it flags rows
whose review_status is not in the same VALID_REVIEW_STATUSES set
starting_naval_forces.gd itself enforces at load time (kept in sync by
comment, not by import, since one is Python and one is GDScript), so the
report's "unresolved" column can never disagree with what the game will
actually accept.
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT / "assets" / "grand_world_1444_naval_forces.json"
DEFAULT_OUTPUT = ROOT / "docs" / "roadmap" / "naval" / "g1_finish_line" / "evidence" / "FL4_2_STARTING_CONTENT_REPORT.md"

# Mirrors StartingNavalForces.VALID_REVIEW_STATUSES in
# scripts/simulation/starting_naval_forces.gd - update both together.
VALID_REVIEW_STATUSES = {"approved placeholder", "approved historical"}
PROVENANCE_FIELDS = ("source", "evidence_class", "confidence", "reviewer", "review_date", "review_status", "note")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if any row is unresolved, without writing the report.")
    return parser.parse_args()


def build_report(data: dict) -> tuple[str, int]:
    fleets = sorted(data.get("fleets", []), key=lambda record: str(record.get("fleet_id", "")))
    lines = [
        "# FL4.2 Starting Naval Content Report",
        "",
        f"Generated by `tools/naval/build_naval_forces_report.py` on {datetime.date.today().isoformat()} "
        f"from `{DEFAULT_INPUT.relative_to(ROOT).as_posix()}` (schema_version {data.get('schema_version')}, "
        f"content_status `{data.get('content_status', '')}`). Regenerate after any starting-fleet content change "
        "rather than hand-editing this file.",
        "",
        "| Fleet | Country | Home port | Ships | Mission | Review status | Reviewer | Review date | Confidence | Unresolved |",
        "|---|---|---:|---:|---|---|---|---|---|---|",
    ]
    unresolved_count = 0
    for record in fleets:
        provenance = record.get("provenance", {}) if isinstance(record.get("provenance"), dict) else {}
        missing_fields = [field for field in PROVENANCE_FIELDS if not str(provenance.get(field, "")).strip()]
        review_status = str(provenance.get("review_status", ""))
        unresolved = bool(missing_fields) or review_status not in VALID_REVIEW_STATUSES
        if unresolved:
            unresolved_count += 1
        lines.append(
            "| {fleet_id} | {country} | {port} | {ships} | {mission} | {status} | {reviewer} | {date} | {confidence} | {flag} |".format(
                fleet_id=record.get("fleet_id", ""),
                country=record.get("country_tag", ""),
                port=record.get("home_port_id", ""),
                ships=len(record.get("ships", []) or []),
                mission=record.get("mission", ""),
                status=review_status or "(missing)",
                reviewer=provenance.get("reviewer", "") or "(missing)",
                date=provenance.get("review_date", "") or "(missing)",
                confidence=provenance.get("confidence", "") or "(missing)",
                flag="YES - " + ", ".join(missing_fields or ["unapproved review_status"]) if unresolved else "no",
            )
        )
    lines.append("")
    lines.append(
        f"**{len(fleets)} fleet(s) reviewed, {unresolved_count} unresolved.**"
        + (" G1 requires zero unresolved rows for every participating country before FL4 can be marked complete." if unresolved_count else " All rows are resolved.")
    )
    lines.append("")
    admiral_rows = sorted({str(record.get("admiral_status", "")) for record in fleets})
    lines.append(
        "**Admiral policy (FL4.3):** every fleet's `admiral_status` currently reads "
        + ", ".join(f"`{status}`" for status in admiral_rows if status)
        + " - see [FL4_ADMIRAL_POLICY.md](FL4_ADMIRAL_POLICY.md) for the approved reasoning, not a gap this report tracks."
    )
    lines.append("")
    return "\n".join(lines), unresolved_count


def main() -> int:
    args = parse_args()
    if not args.input.exists():
        print(f"error: {args.input} does not exist", file=sys.stderr)
        return 1
    data = json.loads(args.input.read_text(encoding="utf-8"))
    report, unresolved_count = build_report(data)
    if args.check:
        if unresolved_count:
            print(f"FAIL: {unresolved_count} unresolved starting naval content row(s).", file=sys.stderr)
            return 1
        print("OK: no unresolved starting naval content rows.")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report + "\n", encoding="utf-8")
    print(f"Wrote {args.output.relative_to(ROOT).as_posix()} ({unresolved_count} unresolved).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
