class_name ProvinceGraph
extends RefCounted

## Runtime view of the baked canonical province graph.
##
## The graph is generated by tools/map_graph/build_province_graph.py and loaded
## once from assets/province_graph.json. Nothing at runtime ever derives
## adjacency from the province texture; this file is the single authority.

const GRAPH_PATH := "res://assets/province_graph.json"

static var _default_instance: ProvinceGraph

var map_size := Vector2i.ZERO
var terrain_costs: Dictionary = {}
var _provinces: Dictionary = {}
var _sorted_land_neighbors: Dictionary = {}
var _sorted_sea_neighbors: Dictionary = {}


static func load_default() -> ProvinceGraph:
	if _default_instance == null:
		_default_instance = ProvinceGraph.new()
		var error := _default_instance._load(GRAPH_PATH)
		if not error.is_empty():
			push_error("Province graph failed to load: %s" % error)
	return _default_instance


func _load(path: String) -> String:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return "missing file %s" % path
	var json := JSON.new()
	if json.parse(file.get_as_text()) != OK:
		return "invalid JSON at line %d: %s" % [json.get_error_line(), json.get_error_message()]
	var data: Dictionary = json.data
	map_size = Vector2i(int(data["map_size"][0]), int(data["map_size"][1]))
	terrain_costs = data.get("terrain_costs", {})
	var provinces: Dictionary = data.get("provinces", {})
	for key in provinces:
		_provinces[int(key)] = provinces[key]
	return ""


func has_province(province_id: int) -> bool:
	return _provinces.has(province_id)


func classification(province_id: int) -> String:
	return String((_provinces.get(province_id, {}) as Dictionary).get("classification", ""))


func is_land(province_id: int) -> bool:
	return classification(province_id) == "land"


func is_impassable(province_id: int) -> bool:
	return classification(province_id) == "impassable"


func is_coastal(province_id: int) -> bool:
	return bool((_provinces.get(province_id, {}) as Dictionary).get("coastal", false))


func province_name(province_id: int) -> String:
	return String((_provinces.get(province_id, {}) as Dictionary).get("name", ""))


func anchor(province_id: int) -> Vector2i:
	var stored = (_provinces.get(province_id, {}) as Dictionary).get("anchor", null)
	if stored is Array and (stored as Array).size() == 2:
		return Vector2i(int(stored[0]), int(stored[1]))
	return Vector2i(-1, -1)


func bounding_rect(province_id: int) -> Rect2i:
	var stored = (_provinces.get(province_id, {}) as Dictionary).get("bbox", null)
	if stored is Array and (stored as Array).size() == 4:
		var values := stored as Array
		var minimum := Vector2i(int(values[0]), int(values[1]))
		var maximum := Vector2i(int(values[2]), int(values[3]))
		return Rect2i(minimum, maximum - minimum + Vector2i.ONE)
	return Rect2i()


func land_neighbors(province_id: int) -> PackedInt32Array:
	# Sorted ascending so every traversal visits neighbours in a stable order.
	if _sorted_land_neighbors.has(province_id):
		return _sorted_land_neighbors[province_id]
	var neighbors := PackedInt32Array()
	var stored: Dictionary = (_provinces.get(province_id, {}) as Dictionary).get("land_neighbors", {})
	for key in stored:
		neighbors.append(int(key))
	neighbors.sort()
	_sorted_land_neighbors[province_id] = neighbors
	return neighbors


func sea_neighbors(province_id: int) -> PackedInt32Array:
	# Sorted ascending, same stability guarantee as land_neighbors(). A water
	# record's sea_neighbors are other water zones; a land record's are its
	# sea exits. The reciprocal of a land exit lives in the water record's
	# land_neighbors, not its sea_neighbors - see tools/naval/build_naval_graph_data.py.
	if _sorted_sea_neighbors.has(province_id):
		return _sorted_sea_neighbors[province_id]
	var neighbors := PackedInt32Array()
	var stored: Dictionary = (_provinces.get(province_id, {}) as Dictionary).get("sea_neighbors", {})
	for key in stored:
		neighbors.append(int(key))
	neighbors.sort()
	_sorted_sea_neighbors[province_id] = neighbors
	return neighbors


func is_water(province_id: int) -> bool:
	return classification(province_id) == "water"


func is_strait(from_id: int, to_id: int) -> bool:
	var straits: Array = (_provinces.get(from_id, {}) as Dictionary).get("straits", [])
	return straits.has(str(to_id))


func move_class(province_id: int) -> String:
	return String((_provinces.get(province_id, {}) as Dictionary).get("move_class", "plains"))


func entry_cost_days(province_id: int) -> int:
	return int(terrain_costs.get(move_class(province_id), 5))


func strait_cost_days() -> int:
	return int(terrain_costs.get("strait_crossing", 4))


func border_pixels(from_id: int, to_id: int) -> int:
	var stored: Dictionary = (_provinces.get(from_id, {}) as Dictionary).get("land_neighbors", {})
	return int(stored.get(str(to_id), 0))


func province_count() -> int:
	return _provinces.size()


func land_province_ids() -> PackedInt32Array:
	var ids := PackedInt32Array()
	for province_id in _provinces:
		if is_land(province_id):
			ids.append(province_id)
	ids.sort()
	return ids
